### ISSUE TITLE
[Strictly 10.0.9] Password Policy 2.0.0

### ISSUE THREAD

**Issue by PVince81** [owncloud/password_policy#17]
### Reason
- This version will depend strictly on 10.0.9 because of the introduction of the IAccountModule API
- Password expiry feature: https://github.com/owncloud/password_policy/issues/2 depending on 10.0.9

### Open tasks
- [x] password expiry:  https://github.com/owncloud/password_policy/issues/2 
- [x] password expiry notifications: https://github.com/owncloud/password_policy/issues/18
- [x] default expiration for existing users with no password history https://github.com/owncloud/password_policy/issues/24
- [x] admin password changes must also be added https://github.com/owncloud/password_policy/issues/25
- [x] :warning: increase min-version to 10.0.9

### QA
- [x] Create release branch release-2.0.0
- [x] Create "$version Testplan" @davitol https://github.com/owncloud/password_policy/issues/43
- [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label)

### Marketing
- [ ] Ping RocketChat channel #marketing
- [x] Check/adapt info.xml stuff https://github.com/owncloud/password_policy/pull/38 / https://github.com/owncloud/password_policy/pull/54 @pmaier
- [x] Check/adapt screenshot - no change required @pmaier
- [x] Blog post or other communication if applicable - will be included in 10.0.9 release communication

### Documentation
- [ ] https://github.com/owncloud/documentation/issues/4273
- [ ] To add to future documentation. **If we want to apply Change pwd at 1st login etc to the Guest users, it is mandatory to add password_policy to the apps whitelist of the guest app**

### Build & Marketplace release

- [x] Bump version in info.xml
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' - https://github.com/owncloud/password_policy/pull/44
- [x] Create github tag for '$version' @patrickjahns
- [x] Build and sign tarball from github tag '$version' @patrickjahns
- [x] Upload to marketplace @patrickjahns
- [x] Send mail to release-coordination with link to this ticket and to the changelog @patrickjahns
- [x] Rename QA milestone to '$version' @patrickjahns
- [x] Add a new 'Unreleased' section in CHANGELOG.md @patrickjahns
- [ ] Create PR to merge changes back to `master` @patrickjahns

### Specifics

- Open tickets before QA can start
- Other specifics for app release

@DeepDiver1975 @patrickjahns

**Comment by PVince81** [comment]
Added https://github.com/owncloud/password_policy/issues/24 to ticket list for the release

**Comment by PVince81** [comment]
Added  "admin password changes must also be added https://github.com/owncloud/password_policy/issues/25"

**Comment by PVince81** [comment]
Remaining things because we can move forward with the release:

- [ ] @pmaier1: please ack the occ command approach here https://github.com/owncloud/password_policy/issues/24 (I want to avoid last minute disagreements)
- [ ] @pmaier1: note, likely no audit for now (missing Symfony events, need future release and admin_audit/splunk adjustments anyway)
- [ ] @pmaier1: need texts here and prepare German translation to copy into transifex: https://github.com/owncloud/password_policy/issues/18#issuecomment-403439985
- [ ] @pmaier1: please adapt info.xml
- [ ] @DeepDiver1975 be ready to run transifex scripts for password policy as soon as https://github.com/owncloud/password_policy/issues/18 is merged
- [ ] @butonic / @DeepDiver1975 need comment on this potential bug, app password destruction https://github.com/owncloud/password_policy/issues/33
- [ ] @jvillafanez please review my JS approach in https://github.com/owncloud/password_policy/issues/18, if ok then we unblock core release
- [ ] @jvillafanez finishes notification PR (unit tests + discard notification) https://github.com/owncloud/password_policy/issues/18, would suggest early merge for transifex as soon as texts are done

**Comment by pmaier1** [comment]
> @pmaier1: please ack the occ command approach here #24 (I want to avoid last minute disagreements)

I don't yet understand all implications, asked in the ticket.

> @pmaier1: note, likely no audit for now (missing Symfony events, need future release and admin_audit/splunk adjustments anyway)

Acceptable for now. Still we should not forget about adding events at least for "password has expired". Password has been changed should already be covered, I guess.

> @pmaier1: need texts here and prepare German translation to copy into transifex: #18 (comment)

On it, maybe we can check together later today.

> @pmaier1: please adapt info.xml

On it.

**Comment by pmaier1** [comment]
Added documentation ticket https://github.com/owncloud/documentation/issues/4273 to OP

**Comment by PVince81** [comment]
Raised https://github.com/owncloud/password_policy/issues/37 for the symfony events

**Comment by pmaier1** [comment]
Created PR for info.xml changes https://github.com/owncloud/password_policy/pull/38 and added to OP

**Comment by jvillafanez** [comment]
> please review my JS approach in #18, if ok then we unblock core release

We'll have to go with it for now.

> finishes notification PR (unit tests + discard notification) #18, would suggest early merge for transifex as soon as texts are done

PR is in mergeable state. Review and QA in progress

**Comment by PVince81** [comment]
- [ ] potential blocker: https://github.com/owncloud/password_policy/issues/47

**Comment by pmaier1** [comment]
Referring to what was stated under "Documentation" in the OP

> If we want to apply Change pwd at 1st login etc to the Guest users, it is mandatory to add password_policy to the apps whitelist of the guest app

This should be added to the default whitelist of the guests app, IMO. Can someone go for a quick PR?

**Comment by pmaier1** [comment]
Please merge this one before release https://github.com/owncloud/password_policy/pull/54. Added some words to info.xml description to state more clearly that policies will also apply to guests.

**Comment by pmaier1** [comment]
> This should be added to the default whitelist of the guests app, IMO. Can someone go for a quick PR?

I think I did it :D https://github.com/owncloud/guests/pull/227

**Comment by PVince81** [comment]
notifications part related to occ got merged.

next up, sync down the transifex translations @DeepDiver1975

**Comment by PVince81** [comment]
- [ ] update doc ticket to match last notifications update and user states

**Comment by PVince81** [comment]
translations were synced already: https://github.com/owncloud/password_policy/commit/26210692afb34738ded5d04042962e4f2d85d8f5

**Comment by PVince81** [comment]
release branch created "release-2.0.0", tickets moved to "qa" milestone

**Comment by patrickjahns** [comment]
Released on the marketplace ✨ - closing
