### ISSUE TITLE
Tracking testing results for Password Policy 2.0.2

### ISSUE THREAD

**Issue by davitol** [owncloud/password_policy#179]
Tested in oC 10.0.10 and with the tarball provided in: https://cloud.owncloud.com/index.php/s/7b8Yx2iU42bkTDX

**Changelog**

- [x] Set max version to 10 for Semver
- [x] First login enforcement fixes https://github.com/owncloud/password_policy/pull/171 **Tested following steps from https://github.com/owncloud/password_policy/pull/171#issuecomment-442023979**
- [x] LDAP login enforcement fixes https://github.com/owncloud/password_policy/pull/173 **Tested following steps https://github.com/owncloud/password_policy/issues/159#issue-378616790**
