### ISSUE TITLE
Tracking testing results for Password Policy 2.1.0.

### ISSUE THREAD

**Issue by davitol** [owncloud/password_policy#269]
# Test Plan Password policy

### 1. web UI
1.1 admin creates a user
1.2 admin changes password of a user
1.3 user changes own password in personal user settings
1.4 user sets own password on lost password page
1.5 user creates a public share (this is using the share API, so no need to test by itself if the share API is tested)

### 2. [User Provisioning API](https://doc.owncloud.org/server/10.0/admin_manual/configuration/user/user_provisioning_api.html)
2.1 [users / adduser](https://doc.owncloud.org/server/10.0/admin_manual/configuration/user/user_provisioning_api.html#users-adduser)
2.2 [users / edituser](https://doc.owncloud.org/server/10.0/admin_manual/configuration/user/user_provisioning_api.html#users-edituser)

### 3. [share API](https://doc.owncloud.org/server/latest/developer_manual/core/ocs-share-api.html)
3.1 [create a new share](https://doc.owncloud.org/server/latest/developer_manual/core/ocs-share-api.html#create-a-new-share)
3.2 [update share](https://doc.owncloud.org/server/latest/developer_manual/core/ocs-share-api.html#update-share)

### 4. occ
4.1 user:add
4.2 user:resetpassword

**Comment by davitol** [comment]
### Tracking testing results for Changelog

Changed

 - [ ] Drop PHP 7.0 - #267
 - [ ] Adjust 'Unable to create user:' expected message text - #243
 - [ ] Use CHAR_SYMBOLS to generate password when no special chars are specified - #233
 - [ ] Drop PHP 5.6 - #211
 - [ ] Implement phpstan and phan - #169

Fixed

 - [ ] Special characters provided shouldn't be empty - #234
 - [ ] Increase width of numeric fields to display 3 digits - #231
 - [ ] Adjust link expiry UI text adding 'maximum' - #226
 - [ ] Cast times to int (phan warning) - #217
