### ISSUE TITLE
Tracking test results for Password Policy 2.0.0.

### ISSUE THREAD

**Issue by davitol** [owncloud/password_policy#43]
[WIP] Pending to add Notification scenarios.

# Test Plan Password policy

### 1. web UI
1.1 admin creates a user
1.2 admin changes password of a user
1.3 user changes own password in personal user settings
1.4 user sets own password on lost password page
1.5 user creates a public share (this is using the share API, so no need to test by itself if the share API is tested)

### 2. [User Provisioning API](https://doc.owncloud.org/server/10.0/admin_manual/configuration/user/user_provisioning_api.html)
2.1 [users / adduser](https://doc.owncloud.org/server/10.0/admin_manual/configuration/user/user_provisioning_api.html#users-adduser)
2.2 [users / edituser](https://doc.owncloud.org/server/10.0/admin_manual/configuration/user/user_provisioning_api.html#users-edituser)

### 3. [share API](https://doc.owncloud.org/server/latest/developer_manual/core/ocs-share-api.html)
3.1 [create a new share](https://doc.owncloud.org/server/latest/developer_manual/core/ocs-share-api.html#create-a-new-share)
3.2 [update share](https://doc.owncloud.org/server/latest/developer_manual/core/ocs-share-api.html#update-share)

### 4. occ
4.1 user:add
4.2 user:resetpassword

### 0 No special password requirements / no link expiration requirements
These tests make sure the app does not block anything if all its settings are disabled
**Test Setup:**
disable all requirements checks

| Test Case | Steps | Expected Result | Results | Comments |
| :-------- | :-----| :-------------- | :-----: | :------- |
|very simple passwords work|set "aaa" as password| The intended action is implemented|1.1 ✅ <br />1.2 ✅<br />1.3 ✅<br />1.4 ✅<br />2.1 ✅<br />2.2 ✅<br />3.1 ✅<br />3.2 ✅<br />4.1 ✅<br />4.2 ✅<br /> ||
|public links without expire date & password work|Create/update a public link with a password and no expire date| Link is created/updated | 3.1 ✅<br />3.2 ✅ ||
|public links without expire date & no password work|Create/update a public link without a password and no expire date| Link is created/updated | 3.1 ✅<br />3.2 ✅ ||
|public links with an expire date far in the future & password work|Create/update a public link with a password and the expire date set to today +1 year| Link is created/updated | 3.1 ✅<br />3.2 ✅ ||
|public links with an expire date far in the future & no password work|Create/update a public link without a password and the expire date set to today +1 year| Link is created/updated | 3.1 ✅<br />3.2 ✅ ||

### 1 Minimum characters required
**Test Setup:**
1. enable "minimum characters" check
2. set "minimum characters" requirement to "8"

| Test Case | Steps | Expected Result | Results | Comments |
| :-------- | :-----| :-------------- | :-----: | :------- |
|Minimum characters required, too short password set|set a password of less than 8 chars| User is notified that the password isn't long enough, setting the password is refused. The intended action is not implemented|1.1 ✅<br />1.2 ✅<br />1.3 ✅<br />1.4✅<br />2.1 ✅<br />2.2 ✅<br />3.1 ✅<br />3.2 ✅<br />4.1 ✅<br />4.2 ✅<br /> ||
|Minimum characters required, long enough password set|set a password of 8 chars| Password is set to the correct value. The intended action is implemented |1.1 ✅<br />1.2 ✅<br />1.3 ✅<br />1.4 ✅<br />2.1 ✅<br />2.2 ✅<br />3.1 ✅<br />3.2 ✅<br />4.1 ✅<br />4.2 ✅<br /> ||
|Enforcement of password protection for shares overrides zero characters requirement|1. set "minimum characters" requirement to "0"<br />2. enable "Enforce password protection" in sharing settings<br />3. As user share a folder with an empty password.| Password is not set and link is not created|1.5 ✅  ||
|Passwords with a length of 0 are not possible|1. set "minimum characters" requirement to "0"<br />2. set an empty password.| The intended action is not implemented|1.1 ✅<br />1.2 ✅<br />1.3 ✅<br />1.4 ✅<br />2.1 ✅<br />2.2 ✅<br />4.1 ✅<br />4.2 ✅<br />  ||
|letters not allowed in "minimum characters" field|set "minimum characters" requirement to "a"|Hint is shown, saying that a number has to be entered| ✅ ||
|negative numbers are not allowed in "minimum characters" field|set "minimum characters" requirement to "-1"|Hint is shown saying that values less than 1 are not allowed| ✅ ||
|"0" is not allowed in "minimum characters" field|set "minimum characters" requirement to "0"|Hint is shown saying that values less than 1 are not allowed| ❌  ||
|empty "minimum characters" field is not allowed|clear "minimum characters" requirements field|Hint is shown, saying that a number has to be entered| ✅  | Fake saving, refreshing the page a zero appears|

### 2 Uppercase letters required
**Test Setup:**
1. enable "uppercase letters" check
2. set "uppercase letters" requirement to "3"

| Test Case | Steps | Expected Result | Results | Comments |
| :-------- | :-----| :-------------- | :-----: | :------- |
|Minimum amount of uppercase letters required, given password does not contain enough uppercase letters | set a password containing less than 3 uppercase letters| User is notified that the password does not contain enough uppercase letters, setting the password is refused. The intended action is not implemented|1.1 ✅ <br />1.2 ✅<br />1.3 ✅<br />1.4 ✅<br />2.1 ✅<br />2.2 ✅<br />3.1 ✅ <br />3.2 ✅<br />4.1 ✅<br />4.2 ✅ <br /> ||
|Minimum amount of uppercase letters required, given password contains enough uppercase letters | set a password containing 3 uppercase letters| Password is set to the correct value. The intended action is implemented|1.1 ✅ <br />1.2 ✅ <br />1.3 ✅ <br />1.4 ✅<br />2.1 ✅<br />2.2 ✅<br />3.1 ✅<br />3.2 ✅<br />4.1 ✅<br />4.2 ✅<br /> ||
|letters not allowed in "uppercase letters" field|set "uppercase letters" requirement to "a"|Hint is shown, saying that a number has to be entered| ✅ ||
|negative numbers are not allowed in "uppercase letters" field|set "uppercase letters" requirement to "-1"|Hint is shown saying that values less than 1 are not allowed| ✅ ||
|"0" is not allowed in "uppercase letters" field|set "uppercase letters" requirement to "0"|Hint is shown saying that values less than 1 are not allowed| ❌  ||
|empty "uppercase letters" field is not allowed|clear "uppercase letters" field|Hint is shown, saying that a number has to be entered| ✅ ||

### 3 Numerals required
**Test Setup:**
1. enable "numbers" check
2. set "numbers" requirement to "3"

| Test Case | Steps | Expected Result | Results | Comments |
| :-------- | :-----| :-------------- | :-----: | :------- |
|Minimum amount of numerals required, given password does not contain enough numerals | set a password containing less than 3 numerals| User is notified that the password does not contain enough numbers, setting the password is refused. The intended action is not implemented|1.1 ✅<br />1.2 ✅<br />1.3 ✅<br />1.4 ✅<br />2.1 ✅<br />2.2 ✅<br />3.1 ✅<br />3.2 ✅<br />4.1 ✅<br />4.2 ✅<br /> ||
|Minimum amount of numerals required, given password contains enough numerals | set a password containing 3 numerals| Password is set to the correct value. The intended action is implemented|1.1 ✅<br />1.2 ✅<br />1.3 ✅<br />1.4 ✅<br />2.1 ✅<br />2.2 ✅<br />3.1 ✅<br />3.2 ✅<br />4.1 ✅<br />4.2 ✅<br /> ||
|letters not allowed in "numbers" field|set "numbers" requirement to "a"|Hint is shown, saying that a number has to be entered| ✅ ||
|negative numbers are not allowed in "numbers" field|set "numbers" requirement to "-1"|Hint is shown saying that values less than 1 are not allowed| ✅ ||
|"0" is not allowed in "numbers" field|set "numbers" requirement to "0"|Hint is shown saying that values less than 1 are not allowed| ✅ ||
|empty "numbers" field is not allowed|clear "numbers" field|Hint is shown, saying that a number has to be entered| ✅ ||

### 4 Special characters required
**Test Setup:**
1. enable "special characters" check
2. set "special characters" requirement to "3"

| Test Case | Steps | Expected Result | Results | Comments |
| :-------- | :-----| :-------------- | :-----: | :------- |
|Minimum amount of special characters required, given password does not contain enough special characters | set a password containing less than 3 special characters| User is notified that the password does not contain enough special characters, setting the password is refused. The intended action is not implemented|1.1 ✅<br />1.2 ✅<br />1.3 ✅ <br />1.4 ✅ <br />2.1 ✅ <br />2.2 ✅<br />3.1 ✅<br />3.2 ✅<br />4.1 ✅<br />4.2 ✅<br /> ||
|Minimum amount of special characters required, given password contains enough special characters | set a password containing 3 special characters| Password is set to the correct value. The intended action is implemented|1.1 ✅<br />1.2 ✅<br />1.3 ✅<br />1.4 ✅<br />2.1 ✅<br />2.2 ✅<br />3.1 ✅<br />3.2 ✅<br />4.1 ✅<br />4.2 ✅<br /> ||
|letters not allowed in "special characters" field|set "special characters" requirement to "a"|Hint is shown, saying that a number has to be entered| ✅ ||
|empty "special characters" field is not allowed|clear "special characters" field|Hint is shown, saying that a number has to be entered| ✅ ||
|"0" is not allowed in "special characters" field|set "special characters" requirement to "0"|Hint is shown saying that values less than 1 are not allowed| ❌  ||
|negative numbers are not allowed in "special characters" field|set "special characters" requirement to "-1"|Hint is shown saying that values less than 1 are not allowed| ✅ ||
|Minimum amount of special characters required, only given special characters are allowed, given password contains forbidden special characters | 1. enable "Define special characters" checkbox<br />2. Define "^ñ/" as special characters.<br />3. set a password containing the 3 special characters "^ñ\"|User is notified that the password contains an invalid special characters, setting the password is refused. The intended action is not implemented |1.1 N/A<br />1.2 N/A<br />1.3 N/A<br />1.4 N/A<br />2.1 N/A<br />2.2 N/A<br />3.1 N/A<br />3.2 N/A<br />4.1 N/A<br />4.2 N/A<br /> ||
|Minimum amount of special characters required, only given special characters are allowed, given password contains one of the allowed special characters | 1. enable "Define special characters" checkbox<br />2. Define "^ñ/" as special characters.<br />3. set a password containing the 3 special characters "///"| Password is set to the correct value. The intended action is implemented|1.1 N/A <br />1.2 N/A<br />1.3 N/A <br />1.4 N/A <br />2.1 N/A <br />2.2 N/A <br />3.1 N/A <br />3.2 N/A <br />4.1 N/A <br />4.2 N/A<br /> ||
|Invalid list of allowed special characters|Define `<#+§$>` as allowed special characters|warning is shown saying that this list is invalid because it is enclosed in `<>`| 🚧 ||
|Emojis in the list of allowed special characters|1. Place an emoji in the list of allowed special characters<br />2. use that emoji in a password|Password is set to the correct value. The intended action is implemented|1.1 ✅<br />1.2 ✅<br />1.3 ✅<br />1.4 ✅<br />2.1 ✅<br />2.2 ✅<br />3.1 ✅<br />3.2 ✅<br />4.1 ✅<br />4.2 ✅<br /> ||

### 5. Link expiration

| Test Case | Steps | Expected Result | Results | Comments |
| :-------- | :-----| :-------------- | :-----: | :------- |
|empty "days until link expires if password is set" field is not allowed|1. Enable "days until link expires if password is set" check.<br />2. clear "days until link expires if password is set" field|Hint is shown, saying that a number has to be entered| ✅ ||
|"0" is not allowed in "days until link expires if password is set" field|1. Enable "days until link expires if password is set" check.<br />2. set "days until link expires if password is set" field to "0"|Hint is shown saying that values less than 1 are not allowed| ✅ ||
|negative numbers are not allowed in "days until link expires if password is set" field|1. Enable "days until link expires if password is set" check.<br />2. set "days until link expires if password is set" field to "-1"|Hint is shown saying that values less than 1 are not allowed| ✅ ||
|empty "days until link expires if password is not set" field is not allowed|1. Enable "days until link expires if password is not set" check.<br />2. clear "days until link expires if password is not set" field|Hint is shown, saying that a number has to be entered| ✅ ||
|"0" is not allowed in "days until link expires if password is not set" field|1. Enable "days until link expires if password is not set" check.<br />2. set "days until link expires if password is not set" field to "0"|Hint is shown saying that values less than 1 are not allowed| :X: ||
|negative numbers are not allowed in "days until link expires if password is not set" field|1. Enable "days until link expires if password is not set" check.<br />2. set "days until link expires if password is not set" field to "-1"|Hint is shown saying that values less than 1 are not allowed| ✅ ||
|Limit max. link expiration if password is set. Try to create a link without expire date.| 1. Enable "days until link expires if password is set" check.<br />2. Set "days until link expires if password is set" to "5"<br />3. Create a public link with a password and no expire date|Notification is shown, saying that the expiration date is required. Link is not created|3.1 ✅  ||
|Limit max. link expiration if password is set. Try to create a link with invalid date.| 1. Enable "days until link expires if password is set" check.<br />2. Set "days until link expires if password is set" to "5"<br />3. Create a public link with a password and expire date of today+7 days|Notification is shown, saying that the expiration date cannot exceed 5 days. Link is not created|3.1 ✅  ||
|Limit max. link expiration if password is set. Try to create a link with a date inside of max. expire date| 1. Enable "days until link expires if password is set" check.<br />2. Set "days until link expires if password is set" to "5"<br />3. Create a public link with a password and expire date of today+4 days|Link is created|3.1 ✅  ||
|Limit max. link expiration if password is not set. Try to create a link without expire date.| 1. Enable "days until link expires if password is not set" check.<br />2. Set "days until link expires if password is not set" to "5"<br />3. Create a public link without a password and no expire date|Notification is shown, saying that the expiration date is required. Link is not created|3.1 ✅  ||
|Limit max. link expiration if password is not set. Try to create a link with invalid date.| 1. Enable "days until link expires if password is not set" check.<br />2. Set "days until link expires if password is not set" to "5"<br />3. Create a public link without a password and expire date of today+7 days|Notification is shown, saying that the expiration date cannot exceed 5 days. Link is not created|3.1 ✅  ||
|Limit max. link expiration if password is not set. Try to create a link with a date inside of max. expire date| 1. Enable "days until link expires if password is not set" check.<br />2. Set "days until link expires if password is not set" to "5"<br />3. Create a public link without a password and expire date of today+4 days|Link is created|3.1 ✅  ||
|Limit max. link expiration if password is set. Delete the expire date of an existing link with password.| 1. Enable "days until link expires if password is set" check.<br />2. Set "days until link expires if password is set" to "5"<br />3. Create a public link with a password and expire date of today+4 days<br />4. Edit the newly created public link and delete the expire date|Notification is shown, saying that the expiration date is required. Link is not updated|3.2 ✅  ||
|Limit max. link expiration if password is set. Change the expire date of an existing link with password to an invalid date.| 1. Enable "days until link expires if password is set" check.<br />2. Set "days until link expires if password is set" to "5"<br />3. Create a public link with a password and expire date of today+4 days<br />4. Edit the newly created public link and set the expire date to today+7 days|Notification is shown, saying that the expiration date cannot exceed 5 days. Link is not updated|3.2 ✅  ||
|Limit max. link expiration if password is set. Change the expire date of an existing link with password to an valid date.| 1. Enable "days until link expires if password is set" check.<br />2. Set "days until link expires if password is set" to "5"<br />3. Create a public link with a password and expire date of today+4 days<br />4. Edit the newly created public link and set the expire date to today+5 days|Link is updated|3.2 ✅  ||
|Limit max. link expiration if password is not set. Delete the expire date of an existing link without a password.| 1. Enable "days until link expires if password is not set" check.<br />2. Set "days until link expires if password is not set" to "5"<br />3. Create a public link without a password and expire date of today+4 days<br />4. Edit the newly created public link and delete the expire date|Notification is shown, saying that the expiration date is required. Link is not updated|3.2 ✅  ||
|Limit max. link expiration if password is not set. Change the expire date of an existing link without a password to an invalid date.| 1. Enable "days until link expires if password is not set" check.<br />2. Set "days until link expires if password is not set" to "5"<br />3. Create a public link without a password and expire date of today+4 days<br />4. Edit the newly created public link and set the expire date to today+7 days|Notification is shown, saying that the expiration date cannot exceed 5 days. Link is not updated|3.2 ✅  ||
|Limit max. link expiration if password is not set. Change the expire date of an existing link without a password to an valid date.| 1. Enable "days until link expires if password is not set" check.<br />2. Set "days until link expires if password is not set" to "5"<br />3. Create a public link without a password and expire date of today+4 days<br />4. Edit the newly created public link and set the expire date to today+5 days|Link is updated|3.2 ✅  ||
|Limit max. link expiration if password is not set. Remove the password of an existing link without an expire date.| 1. Enable "days until link expires if password is not set" check.<br />2. Set "days until link expires if password is not set" to "5"<br />3. Create a public link with a password and no expire date<br />4. Edit the newly created public link and remove the password|Notification is shown, saying that the expiration date is required. Link is not updated|3.2 ✅  ||
|Limit max. link expiration if password is not set. Remove the password of an existing link with an expire date too far in the future.| 1. Enable "days until link expires if password is not set" check.<br />2. Set "days until link expires if password is not set" to "5"<br />3. Create a public link with a password and a expire date of today+14 days<br />4. Edit the newly created public link and remove the password|Notification is shown, saying that the expiration date is required. Link is not updated|3.2 ✅  ||
|Limit max. link expiration if password is not set. Remove the password of an existing link with an expire date within the limits of "link expiration if password is not set"| 1. Enable "days until link expires if password is not set" check.<br />2. Set "days until link expires if password is not set" to "5"<br />3. Create a public link with a password and a expire date of today+4 days<br />4. Edit the newly created public link and remove the password|Link is updated|3.2 ✅  ||
|Limit max. link expiration if password is set. Add a password to an existing link without an expire date.| 1. Enable "days until link expires if password is set" check.<br />2. Set "days until link expires if password is set" to "5"<br />3. Create a public link without a password and no expire date<br />4. Edit the newly created public link and set a password|Notification is shown, saying that the expiration date is required. Link is not updated|3.2 ✅ ||
|Limit max. link expiration if password is set. Add a password to an existing link with an expire date too far in the future.| 1. Enable "days until link expires if password is set" check.<br />2. Set "days until link expires if password is set" to "5"<br />3. Create a public link without a password and a expire date of today+14 days<br />4. Edit the newly created public link and add a password|Notification is shown, saying that the expiration date is required. Link is not updated|3.2 ✅  ||
|Limit max. link expiration if password is set. Add a password to an existing link with an expire date within the limits of "link expiration if password is set"| 1. Enable "days until link expires if password is set" check.<br />2. Set "days until link expires if password is set" to "5"<br />3. Create a public link without a password and a expire date of today+4 days<br />4. Edit the newly created public link and add a password|Link is updated|3.2 ✅  ||

### 6. User Password policies

| Test Case | Steps | Expected Result | Results | Comments |
| :-------- | :-----| :-------------- | :-----: | :------- |
|empty "days until user password expires" field is not allowed|1. Enable "days until user password expires" check.<br />2. clear "days until user password expires" field|Hint is shown, saying that a number has to be entered| :no_entry_sign:  |[ticket](https://github.com/owncloud/password_policy/issues/41#issuecomment-404777496)|
|"0" is not allowed in "days until user password expires" field|1. Enable "days until user password expires" check.<br />2. set "days until user password expires" field to "0"|Hint is shown saying that values less than 1 are not allowed| :no_entry_sign:  |[ticket](https://github.com/owncloud/password_policy/issues/41#issuecomment-404777496)|
|negative numbers are not allowed in "days until user password expires" field|1. Enable "days until user password expires" check.<br />2. set "days until user password expires" field to "-1"|Hint is shown saying that values less than 1 are not allowed| :no_entry_sign:  |[ticket](https://github.com/owncloud/password_policy/issues/41#issuecomment-404777496)|
|User Password expires after the days set passed|1. Enable "days until user password expires" check.<br />2. set "days until user password expires" field to "3"<br />3. Modify server's date to +4 days|Check that the password has expired| ✅ | Instead of changing server date, `set change_time -= - (4*24*3600)`|

### 7. Force change on first login

| Test Case | Steps | Expected Result | Results | Comments |
| :-------- | :-----| :-------------- | :-----: | :------- |
|Password changing is mandatory after the 1st login| 1. Enable "Force change on first login" check.<br />2. Log in with a user for the 1st time | Check you are requested to change the password | ✅ |[details](https://github.com/owncloud/password_policy/issues/43#issuecomment-404775684)|
|Password changing is not longer mandatory after disabling the option|1. Disable "Force change on first login" check.<br />2. Log in with a user for the 1st time |Check you are no longer requested to change the password| ✅ |[details](https://github.com/owncloud/password_policy/issues/43#issuecomment-404775684)|

**Comment by PVince81** [comment]
- [ ] test impersonate (I'll have a look)
- [ ] test totp
- [ ] test oauth

test these with a password expired and before new password entered, then also after password is entered

**Comment by PVince81** [comment]
- [x] TEST: with user-key encryption, changing password in "password expired" form properly resets the encryption key. Files uploaded before that can be downloaded.

**Comment by PVince81** [comment]
Tested 7 as follows:

1. Login as admin
1. Create one user "user1" (pre-existing)
1. Set rule to "force change password on login"
1. Create one user "user2" (created after policy)
1. Create another user "user3" (created after policy, but will disable policy before login)
1. Log out
1. Login as "user1" -> password change prompt is there, can be changed
1. Login as "user2" -> password change propmt is there, can be changed
1. As admin, remove "force change password on login"
1. Login as "user3" -> no password prompt
:white_check_mark:

**Comment by PVince81** [comment]
- [ ] TEST: redirect to correct page after "force change password on login" password prompt

**Comment by davitol** [comment]
- [ ] TEST: guest app + PasswordPolicy. Password Policy should be in guest app whitelist (see Documentation section in 1st post)

**Comment by sharidas** [comment]
Below is how I tested emoji for 4:
- Minimum 3 special characters were set. Also defined the special characters as `#!:bowtie::heartbeat:;)` were set.
- [x] Admin user created `user1` with password `#!:bowtie:`
- [x] Admin updates the password of `user1` with password `#!#`
- [x] `user1` password is reset from the link obtained through email to `#!:bowtie:;)`
- [x] `user1` resets password from personal settings page

Created `user2` using user provisioning API:
- [x] Here is the command executed:
```
➜  owncloud2 git:(stable10) ✗ curl -X POST http://admin:admin@localhost/testing2/ocs/v1.php/cloud/users -d userid="user2" -d password="#!;)"
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message/>
 </meta>
 <data/>
</ocs>
➜  owncloud2 git:(stable10) ✗ 
```
- [x] Updated the email for `user2`:
```
➜  owncloud2 git:(stable10) ✗ curl -X PUT http://admin:admin@localhost/testing2/ocs/v1.php/cloud/users/user2 -d key="email" -d value="hari.sujith@gmail.com"
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message/>
 </meta>
 <data/>
</ocs>
➜  owncloud2 git:(stable10) ✗
```
Verified that `user2` is created and the email id is also set. Was able to login to `user2` successfully

- [x] Created public link using share API. Below are the console output:
```
➜  owncloud2 git:(stable10) ✗ curl --user user1:bowtie\:\:\; http://localhost/testing2/ocs/v1.php/apps/files_sharing/api/v1/shares --data 'path=to_group1&shareType=3&permissions=1&name=to_group1_testing'
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message/>
 </meta>
 <data>
  <id>1</id>
  <share_type>3</share_type>
  <uid_owner>user1</uid_owner>
  <displayname_owner>user1</displayname_owner>
  <permissions>1</permissions>
  <stime>1531731695</stime>
  <parent/>
  <expiration/>
  <token>CDLa71Zc2yNLPLZ</token>
  <uid_file_owner>user1</uid_file_owner>
  <displayname_file_owner>user1</displayname_file_owner>
  <path>/to_group1</path>
  <item_type>folder</item_type>
  <mimetype>httpd/unix-directory</mimetype>
  <storage_id>home::user1</storage_id>
  <storage>7</storage>
  <item_source>61</item_source>
  <file_source>61</file_source>
  <file_parent>52</file_parent>
  <file_target>/to_group1</file_target>
  <share_with/>
  <share_with_displayname/>
  <name>to_group1_testing</name>
  <url>http://localhost/testing2/index.php/s/CDLa71Zc2yNLPLZ</url>
  <mail_send>0</mail_send>
 </data>
</ocs>
➜  owncloud2 git:(stable10) ✗ curl --user user1:"bowtie::;" http://localhost/testing2/ocs/v1.php/apps/files_sharing/api/v1/shares/1 --request PUT --data 'expireDate=2018-09-03&name=to_group1_testing'                            
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message/>
 </meta>
 <data>
  <id>1</id>
  <share_type>3</share_type>
  <uid_owner>user1</uid_owner>
  <displayname_owner>user1</displayname_owner>
  <permissions>1</permissions>
  <stime>1531731695</stime>
  <parent/>
  <expiration>2018-09-03 00:00:00</expiration>
  <token>CDLa71Zc2yNLPLZ</token>
  <uid_file_owner>user1</uid_file_owner>
  <displayname_file_owner>user1</displayname_file_owner>
  <path>/to_group1</path>
  <item_type>folder</item_type>
  <mimetype>httpd/unix-directory</mimetype>
  <storage_id>home::user1</storage_id>
  <storage>7</storage>
  <item_source>61</item_source>
  <file_source>61</file_source>
  <file_parent>52</file_parent>
  <file_target>/to_group1</file_target>
  <share_with/>
  <share_with_displayname/>
  <name>to_group1_testing</name>
  <url>http://localhost/testing2/index.php/s/CDLa71Zc2yNLPLZ</url>
  <mail_send>0</mail_send>
 </data>
</ocs>
➜  owncloud2 git:(stable10) ✗ 
```
- [x] Using occ command, created `user3` and reset the password. Console output is pasted below:
```
➜  owncloud2 git:(stable10) ✗ ./occ user:add user3 
Cannot load Xdebug - it was already loaded
Enter password: 
Confirm password: 
The user "user3" was created successfully
➜  owncloud2 git:(stable10) ✗./occ user:resetpassword user3
Cannot load Xdebug - it was already loaded
Enter a new password: 
Confirm the new password: 
Successfully reset password for user3
➜  owncloud2 git:(stable10) ✗ 
```

**Comment by davitol** [comment]
**Known issues**
- [ ] Password policy pattern 'different than last passwords' applies to one pwd more than the value set https://github.com/owncloud/password_policy/issues/57
- [ ]  Notifications of delete user are kept in oc_notifications table https://github.com/owncloud/password_policy/issues/53

**Comment by PVince81** [comment]
@davitol did you add the additional tests to the original test plan ?

**Comment by davitol** [comment]
@PVince81 Not the related to notification, I will add them to the template.
