### ISSUE TITLE
Automated tests for password_policy (part 1)

### ISSUE THREAD

**Issue by phil-davis** [owncloud/password_policy#58]
Make automated tests for the password_policy app, both API and webUI-based.

- [x] tests that confirm the app settings configuration page all works #108 #111 #116 #117 
- [x] check various password complexity combinations when users reset a forgotten password #120 
- [x] check various password complexity combinations when users change their password #121
- [x] check various password complexity combinations for the user provisioning API add user #123 and change password #125
- [x] check various password complexity combinations for the ``occ`` reset password command #130 
- [x] check various password complexity combinations for the ``occ`` add user command #127

**Comment by phil-davis** [comment]
@patrickjahns thoughts/comments?

**Comment by phil-davis** [comment]
See https://github.com/owncloud/QA/issues/574 which will create the test plan for the password_policy app. That should be reviewed to check that the list of general automation areas above covers what is reasonable from the test plan.

**Comment by phil-davis** [comment]
ToDo later:
- [ ] check various password complexity combinations when the admin adds a user in the ``user_management`` app
- [ ] check various password complexity combinations when the admin changes a user password in the ``user_management`` app

These require both ``password_policy`` and ``user_management`` apps installed together. See https://github.com/owncloud/QA/issues/585 for discussion.

**Comment by phil-davis** [comment]
See issue #126 for remaining items.
This first part is done.
